name: Build

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: RakambdaOrg/rakambda-github-workflows/.github/workflows/gradle-build.yml@main
    with:
      java-version: ${{ vars.JAVA_VERSION }}
      artifact-name: Gradle-Libs

  dropbox:
    uses: RakambdaOrg/rakambda-github-workflows/.github/workflows/dropbox-publish-artifact.yml@main
    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    needs:
      - build
    with:
      artifact-name: Gradle-Libs
      source: "ftpfetcher-shaded.jar"
      target: "/Documents/JARs/FTPFetcher.jar"
      environment: DropboxPersonal
    secrets:
      dropbox-token: ${{ secrets.DROPBOX_TOKEN }}

  docker:
    uses: RakambdaOrg/rakambda-github-workflows/.github/workflows/gradle-jib-publish.yml@main
    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    needs:
      - build
    with:
      java-version: ${{ vars.JAVA_VERSION }}
      docker-image: ${{ vars.DOCKER_IMAGE }}
      docker-tag: latest
      environment: DockerSelfHosted
    secrets:
      docker-repo: ${{ secrets.DOCKER_REPO }}
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-token: ${{ secrets.DOCKER_TOKEN }}
